apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-spa-demo 
  name: service-spa-demo
spec:
  type: ClusterIP
  ports:
  - name: service-port-spa-demo
    port: 80
    protocol: TCP
  selector:
    deployment-label-key: deployment-label-spa-demo    